version: '3.9'

services:
  mysql:
    image: mysql:8.2
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=secret
      - MYSQL_USER=my_user
      - MYSQL_DATABASE=myApp
